Name:           ros-lunar-pluginlib
Version:        1.11.2
Release:        0%{?dist}
Summary:        ROS pluginlib package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/pluginlib
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-lunar-class-loader
Requires:       ros-lunar-rosconsole
Requires:       ros-lunar-roslib >= 1.11.1
Requires:       tinyxml2-devel
BuildRequires:  boost-devel
BuildRequires:  ros-lunar-catkin >= 0.5.68
BuildRequires:  ros-lunar-class-loader
BuildRequires:  ros-lunar-cmake-modules
BuildRequires:  ros-lunar-rosconsole
BuildRequires:  ros-lunar-roslib >= 1.11.1
BuildRequires:  tinyxml2-devel

%description
The pluginlib package provides tools for writing and dynamically loading plugins
using the ROS build infrastructure. To work, these tools require plugin
providers to register their plugins in the package.xml of their package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Wed Nov 15 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.11.2-0
- Autogenerated by Bloom

* Fri Oct 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.11.1-0
- Autogenerated by Bloom

* Thu Jul 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.11.0-0
- Autogenerated by Bloom

* Mon Mar 27 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.10.5-0
- Autogenerated by Bloom

* Wed Feb 22 2017 Mikael Arguedas <mikael@osrfoundation.org> - 1.10.4-0
- Autogenerated by Bloom

